# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: pulseaudio 0.0.10 ruby lib

Gem::Specification.new do |s|
  s.name = "pulseaudio".freeze
  s.version = "0.0.10"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Kasper Johansen".freeze]
  s.date = "2018-04-10"
  s.description = "Ruby-library for controlling PulseAudio via 'pactl'.".freeze
  s.email = "k@spernj.org".freeze
  s.executables = ["pulseaudio_volume.rb".freeze]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/pulseaudio_volume.rb",
    "gfx/volume_0.png",
    "gfx/volume_100.png",
    "gfx/volume_33.png",
    "gfx/volume_66.png",
    "gui/choose_active_sink/choose_active_sink.glade",
    "gui/choose_active_sink/choose_active_sink.rb",
    "gui/choose_active_sink_gtk3/choose_active_sink.glade",
    "gui/choose_active_sink_gtk3/choose_active_sink_gtk3.rb",
    "include/pulseaudio_events.rb",
    "include/pulseaudio_gui.rb",
    "include/pulseaudio_sink.rb",
    "include/pulseaudio_sink_input.rb",
    "include/pulseaudio_source.rb",
    "include/pulseaudio_source_output.rb",
    "lib/pulseaudio.rb",
    "pulseaudio.gemspec",
    "spec/pulseaudio_spec.rb",
    "spec/spec_helper.rb",
    "test_scripts/choose_active_sink.rb",
    "test_scripts/choose_active_sink_gtk3.rb",
    "test_scripts/set_active.rb"
  ]
  s.homepage = "http://github.com/kaspernj/pulseaudio".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "2.6.13".freeze
  s.summary = "Ruby-library for controlling PulseAudio.".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<autogc>.freeze, [">= 0"])
      s.add_runtime_dependency(%q<wref>.freeze, [">= 0.0.8"])
      s.add_runtime_dependency(%q<gir_ffi>.freeze, [">= 0"])
      s.add_runtime_dependency(%q<gtk3assist>.freeze, [">= 0"])
      s.add_runtime_dependency(%q<gettext>.freeze, [">= 0"])
      s.add_runtime_dependency(%q<knjrbfw>.freeze, [">= 0.0.113"])
      s.add_development_dependency(%q<rspec>.freeze, ["~> 2.8.0"])
      s.add_development_dependency(%q<bundler>.freeze, [">= 1.0.0"])
      s.add_development_dependency(%q<jeweler>.freeze, ["= 2.3.9"])
    else
      s.add_dependency(%q<autogc>.freeze, [">= 0"])
      s.add_dependency(%q<wref>.freeze, [">= 0.0.8"])
      s.add_dependency(%q<gir_ffi>.freeze, [">= 0"])
      s.add_dependency(%q<gtk3assist>.freeze, [">= 0"])
      s.add_dependency(%q<gettext>.freeze, [">= 0"])
      s.add_dependency(%q<knjrbfw>.freeze, [">= 0.0.113"])
      s.add_dependency(%q<rspec>.freeze, ["~> 2.8.0"])
      s.add_dependency(%q<bundler>.freeze, [">= 1.0.0"])
      s.add_dependency(%q<jeweler>.freeze, ["= 2.3.9"])
    end
  else
    s.add_dependency(%q<autogc>.freeze, [">= 0"])
    s.add_dependency(%q<wref>.freeze, [">= 0.0.8"])
    s.add_dependency(%q<gir_ffi>.freeze, [">= 0"])
    s.add_dependency(%q<gtk3assist>.freeze, [">= 0"])
    s.add_dependency(%q<gettext>.freeze, [">= 0"])
    s.add_dependency(%q<knjrbfw>.freeze, [">= 0.0.113"])
    s.add_dependency(%q<rspec>.freeze, ["~> 2.8.0"])
    s.add_dependency(%q<bundler>.freeze, [">= 1.0.0"])
    s.add_dependency(%q<jeweler>.freeze, ["= 2.3.9"])
  end
end

