# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "pulseaudio"
  s.version = "0.0.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kasper Johansen"]
  s.date = "2012-09-19"
  s.description = "Ruby-library for controlling PulseAudio via 'pactl'."
  s.email = "k@spernj.org"
  s.executables = ["pulseaudio_volume.rb"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/pulseaudio_volume.rb",
    "gfx/volume_0.png",
    "gfx/volume_100.png",
    "gfx/volume_33.png",
    "gfx/volume_66.png",
    "gui/choose_active_sink/choose_active_sink.glade",
    "gui/choose_active_sink/choose_active_sink.rb",
    "gui/choose_active_sink_gtk3/choose_active_sink.glade",
    "gui/choose_active_sink_gtk3/choose_active_sink_gtk3.rb",
    "include/pulseaudio_events.rb",
    "include/pulseaudio_gui.rb",
    "include/pulseaudio_sink.rb",
    "include/pulseaudio_sink_input.rb",
    "include/pulseaudio_source.rb",
    "include/pulseaudio_source_output.rb",
    "lib/pulseaudio.rb",
    "pulseaudio.gemspec",
    "spec/pulseaudio_spec.rb",
    "spec/spec_helper.rb",
    "test_scripts/choose_active_sink.rb",
    "test_scripts/choose_active_sink_gtk3.rb",
    "test_scripts/set_active.rb"
  ]
  s.homepage = "http://github.com/kaspernj/pulseaudio"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Ruby-library for controlling PulseAudio."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<wref>, [">= 0"])
      s.add_runtime_dependency(%q<gir_ffi>, [">= 0"])
      s.add_runtime_dependency(%q<gtk3assist>, [">= 0"])
      s.add_runtime_dependency(%q<gettext>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.3"])
    else
      s.add_dependency(%q<wref>, [">= 0"])
      s.add_dependency(%q<gir_ffi>, [">= 0"])
      s.add_dependency(%q<gtk3assist>, [">= 0"])
      s.add_dependency(%q<gettext>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
    end
  else
    s.add_dependency(%q<wref>, [">= 0"])
    s.add_dependency(%q<gir_ffi>, [">= 0"])
    s.add_dependency(%q<gtk3assist>, [">= 0"])
    s.add_dependency(%q<gettext>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.8.0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, [">= 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
  end
end

